#!/bin/bash
# combustion: network

# Generate the passwd hash with "openssl passwd -6", default root password is "linux"
echo 'root:$6$NOV0h.mjArgm2igm$W.Nqa.A6vrx1D6ZeNDLq8QdF9uxfd9hF.sJImK4Z9RzF1LHk/D8MFOT9DbKu76zihidoJcZv3/Ye783qDJ075/' | chpasswd -e
mkdir -pm700 /root/.ssh/
# IMPORTANT: ssh-rsa hostkey algorithm doesn't work anymore with terraform and recent sshd, please generate ecdsa keys by `ssh-keygen -t ecdsa` instead
# Content of id_ecdsa_shared.pub file 
cat << EOF >> /root/.ssh/authorized_keys
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCShjA+YztToIkdsS7414qUDDyHbn+v8LElnKzosO/Z5NQZIWhXibg4dexRA4C9Htc2d0Mzg4E8eAnjoC2vXdvU= Unsafe ECDSA Shared Key
EOF
systemctl enable sshd.service
# Leave a marker
echo "Configured with Combustion" > /etc/issue.d/combustion
